"""
LinkedInWatcher — Silver-tier LinkedIn notification stub.

Behavior (stub):
  - Polls Needs_Action/ every POLL_INTERVAL seconds.
  - Detects files with LINKEDIN_ prefix that lack a companion .meta.md note.
  - Creates a LINKEDIN_<stem>.meta.md in Needs_Action/ with proper frontmatter.

Stub note:
  Full implementation would use Playwright to scrape LinkedIn notifications
  (connection requests, messages, job alerts) and drop LINKEDIN_<id>.json or
  LINKEDIN_<id>.md files into Needs_Action/ directly.

Usage:
    python watchers/linkedin_watcher.py
"""

import signal
import sys
from datetime import datetime, timezone
from pathlib import Path

# Allow running from project root or from watchers/ directly
_HERE = Path(__file__).parent
_VAULT_ROOT = _HERE.parent

sys.path.insert(0, str(_HERE))
from base_watcher import BaseWatcher  # noqa: E402


VAULT_ROOT = _VAULT_ROOT
NEEDS_ACTION_DIR = VAULT_ROOT / "Needs_Action"
LOG_DIR = VAULT_ROOT / "Logs"
POLL_INTERVAL = 15  # seconds

LINKEDIN_PREFIX = "LINKEDIN_"


class LinkedInWatcher(BaseWatcher):
    """
    Stub watcher that monitors Needs_Action/ for LINKEDIN_ prefixed files
    and creates companion metadata notes.

    A LINKEDIN_ file is expected to be placed by an upstream process (manual
    drop, Playwright scraper, or webhook). This watcher's job is to detect
    them and produce structured .meta.md notes for the Obsidian workflow.
    """

    def __init__(self) -> None:
        super().__init__(
            watch_dir=NEEDS_ACTION_DIR,
            interval=POLL_INTERVAL,
            log_dir=LOG_DIR,
        )
        NEEDS_ACTION_DIR.mkdir(parents=True, exist_ok=True)
        self.logger.info("LinkedInWatcher (stub) initialized.")
        self.logger.info("Watching     : %s", NEEDS_ACTION_DIR)
        self.logger.info("Trigger      : files prefixed '%s'", LINKEDIN_PREFIX)
        self.logger.info("Poll interval: %ds", POLL_INTERVAL)

    # ------------------------------------------------------------------
    # BaseWatcher interface
    # ------------------------------------------------------------------

    def process_file(self, file_path: Path) -> None:
        """Create a companion .meta.md note for a LINKEDIN_ file."""
        meta_name = f"{file_path.stem}.meta.md"
        meta_path = NEEDS_ACTION_DIR / meta_name

        if meta_path.exists():
            self.logger.debug("Meta already exists, skipping: %s", meta_name)
            return

        now = datetime.now(timezone.utc)
        try:
            stat = file_path.stat()
            size_bytes = stat.st_size
        except OSError:
            size_bytes = 0

        content = f"""\
---
source: linkedin
original_file: {file_path.name}
detected_at: {now.strftime("%Y-%m-%d %H:%M:%S UTC")}
size_bytes: {size_bytes}
status: needs_action
---

# LinkedIn Item — {file_path.stem}

| Field        | Value                                   |
|--------------|-----------------------------------------|
| File         | `{file_path.name}`                      |
| Detected At  | {now.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| Size         | {size_bytes / 1024:.2f} KB              |
| Status       | needs_action                            |

## Action Required

Review `{file_path.name}` and take appropriate action
(connection request, message reply, job alert, etc.).

---
*Auto-generated by LinkedInWatcher (stub) on {now.strftime("%Y-%m-%d")}.*
"""
        try:
            meta_path.write_text(content, encoding="utf-8")
            self.logger.info("Meta note -> %s", meta_name)
        except OSError as exc:
            self.logger.error(
                "Failed to write meta for %s: %s", file_path.name, exc
            )

    # ------------------------------------------------------------------
    # Poll loop
    # ------------------------------------------------------------------

    def _scan(self) -> None:
        """Find LINKEDIN_ files without a companion .meta.md and process them."""
        try:
            entries = sorted(NEEDS_ACTION_DIR.iterdir())
        except OSError as exc:
            self.logger.error("Cannot read Needs_Action: %s", exc)
            return

        targets = [
            p
            for p in entries
            if p.is_file()
            and p.name.startswith(LINKEDIN_PREFIX)
            and not p.name.endswith(".meta.md")
            and not p.name.startswith(".")
        ]

        if not targets:
            self.logger.debug("No unprocessed LINKEDIN_ files.")
            return

        self.logger.info("Found %d LINKEDIN_ file(s) to process.", len(targets))
        for fp in targets:
            self.process_file(fp)

    def run(self) -> None:
        """Start the polling loop. Runs until stopped."""
        self._running = True
        self.logger.info("LinkedInWatcher started. Press Ctrl+C to stop.")

        while self._running:
            self.logger.debug("--- Poll cycle ---")
            self._scan()
            self._sleep()

        self.logger.info("LinkedInWatcher stopped.")


# ------------------------------------------------------------------
# Entry point
# ------------------------------------------------------------------

def _handle_signal(signum, frame):  # noqa: ANN001
    print("\n[linkedin_watcher] Signal received, shutting down…")
    sys.exit(0)


if __name__ == "__main__":
    signal.signal(signal.SIGINT, _handle_signal)
    signal.signal(signal.SIGTERM, _handle_signal)

    watcher = LinkedInWatcher()
    watcher.run()
