"""
LinkedInPoster — Playwright script that submits a post to LinkedIn.

Reuses the persistent browser session from ~/ai-secrets/linkedin_session/
(shared with LinkedInWatcher — no re-login required if watcher ran first).

Called by approval_watcher.py when a linkedin_post APPROVAL_*.md is moved
to Approved/.  Can also be run directly for testing.

Usage:
    python Scripts/linkedin_poster.py --content "Your post text here"
    python Scripts/linkedin_poster.py --draft Plans/DRAFT_POST_2026-03-20.md
    python Scripts/linkedin_poster.py --dry-run --content "Test post"

Exit codes:
    0  Posted successfully
    1  Post failed (see stderr / Logs/LinkedInPoster.log)
    2  Session not active — manual login required (run linkedin_watcher.py first)
    3  Bad arguments / file not found
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from playwright.sync_api import Browser, BrowserContext, Page, sync_playwright

# ── paths ─────────────────────────────────────────────────────────────────────
_HERE       = Path(__file__).parent
_VAULT_ROOT = _HERE.parent

LOG_DIR     = _VAULT_ROOT / "Logs"
LOG_FILE    = LOG_DIR / "LinkedInPoster.log"
SESSION_DIR = Path.home() / "ai-secrets" / "linkedin_session"
ACTIVITY_LOG = _VAULT_ROOT / "Logs" / "ActivityLog.md"

LOG_DIR.mkdir(exist_ok=True)

# ── logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)-8s] LinkedInPoster — %(message)s",
    handlers=[
        logging.StreamHandler(sys.stderr),
        logging.FileHandler(str(LOG_FILE), encoding="utf-8"),
    ],
)
log = logging.getLogger(__name__)

# ── LinkedIn selectors (multiple fallbacks per element) ───────────────────────
# LinkedIn updates their HTML frequently; we try each selector in order.

# "Start a post" button on the feed
SHARE_BOX_SELECTORS = [
    ".share-box-feed-entry__trigger",
    "[data-control-name='share.sharebox_button']",
    "button.artdeco-button--muted",
    "[class*='share-box'][class*='trigger']",
    "button[aria-label*='post']",
    "button[aria-label*='Post']",
    ".editor-placeholder",                      # sometimes the box itself is clickable
]

# The Quill rich-text editor that appears after clicking "Start a post"
EDITOR_SELECTORS = [
    ".ql-editor[contenteditable='true']",
    "[data-placeholder*='What']",
    ".share-creation-state__editor [contenteditable]",
    "[class*='editor'][contenteditable='true']",
    "div[role='textbox']",
]

# "Post" submit button inside the share modal
POST_BUTTON_SELECTORS = [
    ".share-actions__primary-action",
    "button.share-actions__primary-action",
    "[data-control-name='share.post']",
    "button[class*='share'][class*='primary']",
    "button[aria-label='Post']",
    "button[aria-label='Share']",
]

FEED_URL    = "https://www.linkedin.com/feed/"
NAV_SELECTOR = "#global-nav"

MAX_POST_CHARS = 3000  # LinkedIn hard limit


# ── content helpers ───────────────────────────────────────────────────────────

def extract_post_from_draft(draft_path: Path) -> str:
    """
    Read a DRAFT_POST_*.md file and return only the post body.
    Looks for content between '## Post Content' and the next '##' heading.
    """
    text = draft_path.read_text(encoding="utf-8")
    match = re.search(
        r"## Post Content\s*\n(.*?)(?=\n## |\Z)",
        text,
        re.DOTALL,
    )
    if not match:
        raise ValueError(
            f"Could not find '## Post Content' section in {draft_path}. "
            "Make sure the draft was generated by SKILL-008."
        )
    return match.group(1).strip()


def _log_activity(line: str) -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    try:
        with ACTIVITY_LOG.open("a", encoding="utf-8") as f:
            f.write(f"[{ts}] {line}\n")
    except OSError:
        pass


# ── browser helpers ───────────────────────────────────────────────────────────

def _try_click(page: Page, selectors: list[str], description: str, timeout: int = 5000) -> bool:
    """Try each selector in order; return True if one was found and clicked."""
    for sel in selectors:
        try:
            el = page.query_selector(sel)
            if el and el.is_visible():
                el.click()
                log.info("Clicked %s via selector: %s", description, sel)
                return True
        except Exception:
            continue
    log.warning("Could not click %s — tried %d selector(s)", description, len(selectors))
    return False


def _wait_for_any(page: Page, selectors: list[str], timeout: int = 10000) -> str | None:
    """Return the first selector that appears within timeout ms, or None."""
    deadline = time.monotonic() + timeout / 1000
    while time.monotonic() < deadline:
        for sel in selectors:
            try:
                el = page.query_selector(sel)
                if el and el.is_visible():
                    return sel
            except Exception:
                continue
        time.sleep(0.3)
    return None


# ── core poster ───────────────────────────────────────────────────────────────

class LinkedInPoster:
    def __init__(self, dry_run: bool = False) -> None:
        self.dry_run = dry_run
        self._pw      = None
        self._context: BrowserContext | None = None
        self._page:    Page | None = None

    # ── browser lifecycle ─────────────────────────────────────────────────

    def _launch(self) -> None:
        SESSION_DIR.mkdir(parents=True, exist_ok=True)
        log.info("Launching Chromium with session: %s", SESSION_DIR)
        self._pw = sync_playwright().start()
        self._context = self._pw.chromium.launch_persistent_context(
            user_data_dir=str(SESSION_DIR),
            headless=False,          # LinkedIn detects headless and may block
            args=["--no-sandbox", "--disable-dev-shm-usage"],
            viewport={"width": 1280, "height": 900},
        )
        self._page = (
            self._context.pages[0]
            if self._context.pages
            else self._context.new_page()
        )

    def _ensure_logged_in(self) -> bool:
        log.info("Navigating to LinkedIn feed and checking session…")
        self._page.goto(FEED_URL, wait_until="domcontentloaded", timeout=30_000)
        try:
            self._page.wait_for_selector(NAV_SELECTOR, timeout=15_000)
            log.info("LinkedIn session active.")
            return True
        except Exception:
            log.warning(
                "Session not active. Open linkedin_watcher.py first to log in, "
                "then retry. Waiting 120 s for manual login…"
            )
        try:
            self._page.wait_for_selector(NAV_SELECTOR, timeout=120_000)
            log.info("Login detected.")
            return True
        except Exception:
            log.error("Login timed out.")
            return False

    def _close(self) -> None:
        try:
            if self._context:
                self._context.close()
            if self._pw:
                self._pw.stop()
        except Exception as exc:
            log.debug("Browser close error: %s", exc)

    # ── posting flow ──────────────────────────────────────────────────────

    def _open_share_box(self) -> bool:
        """Click 'Start a post' to open the share dialog."""
        log.info("Opening share box…")
        self._page.wait_for_load_state("networkidle", timeout=15_000)

        # Small pause so feed fully renders
        time.sleep(1.5)

        if not _try_click(self._page, SHARE_BOX_SELECTORS, "'Start a post'"):
            return False

        # Wait for editor to appear
        found = _wait_for_any(self._page, EDITOR_SELECTORS, timeout=10_000)
        if not found:
            log.error("Editor did not appear after clicking share box.")
            return False

        log.info("Share dialog open.")
        return True

    def _type_content(self, content: str) -> bool:
        """Focus the editor and type/paste the post content."""
        found_sel = _wait_for_any(self._page, EDITOR_SELECTORS, timeout=8_000)
        if not found_sel:
            log.error("Cannot find editor to type into.")
            return False

        editor = self._page.query_selector(found_sel)
        if not editor:
            return False

        editor.click()
        time.sleep(0.5)

        # Use clipboard paste for speed and to preserve line-breaks
        self._page.evaluate(
            """(text) => {
                const el = document.activeElement || document.querySelector('.ql-editor');
                if (!el) return;
                const dt = new DataTransfer();
                dt.setData('text/plain', text);
                el.dispatchEvent(new ClipboardEvent('paste', {
                    clipboardData: dt,
                    bubbles: true,
                    cancelable: true,
                }));
            }""",
            content,
        )

        # Fallback: if paste didn't work, type character by character (slower)
        time.sleep(1.0)
        typed_text = editor.inner_text().strip()
        if not typed_text:
            log.info("Paste method failed — falling back to keyboard.type()")
            editor.click()
            self._page.keyboard.type(content, delay=10)

        time.sleep(0.5)

        # Verify content entered
        final_text = editor.inner_text().strip()
        if not final_text:
            log.error("Editor appears empty after typing.")
            return False

        log.info("Content entered (%d chars).", len(final_text))
        return True

    def _submit_post(self) -> bool:
        """Click the Post/Share button to submit."""
        log.info("Submitting post…")

        # The Post button is sometimes disabled briefly while content processes
        for attempt in range(5):
            found = _wait_for_any(self._page, POST_BUTTON_SELECTORS, timeout=4_000)
            if found:
                btn = self._page.query_selector(found)
                if btn and not btn.get_attribute("disabled"):
                    break
            time.sleep(1)
        else:
            log.error("Post button not found or still disabled after 5 attempts.")
            return False

        if not _try_click(self._page, POST_BUTTON_SELECTORS, "Post button"):
            return False

        # Wait for confirmation: modal closes and feed refreshes
        try:
            self._page.wait_for_selector(
                ".share-creation-state, [class*='share-modal']",
                state="detached",
                timeout=15_000,
            )
            log.info("Share modal closed — post submitted.")
        except Exception:
            log.warning("Could not confirm modal closure; post may still have succeeded.")

        # Extra check: wait for feed reload
        time.sleep(2)
        log.info("Post submission complete.")
        return True

    # ── public API ────────────────────────────────────────────────────────

    def post(self, content: str) -> bool:
        """
        Post `content` to LinkedIn.
        Returns True on success, False on failure.
        """
        if len(content) > MAX_POST_CHARS:
            log.error(
                "Content exceeds LinkedIn limit: %d chars (max %d).",
                len(content), MAX_POST_CHARS,
            )
            return False

        if self.dry_run:
            log.info("[DRY-RUN] Would post to LinkedIn (%d chars):\n%s", len(content), content)
            return True

        self._launch()
        try:
            if not self._ensure_logged_in():
                return False
            if not self._open_share_box():
                return False
            if not self._type_content(content):
                return False
            if not self._submit_post():
                return False
            return True
        finally:
            self._close()


# ── entrypoint ────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Post content to LinkedIn via Playwright",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python Scripts/linkedin_poster.py --content "My post text"
  python Scripts/linkedin_poster.py --draft Plans/DRAFT_POST_2026-03-20.md
  python Scripts/linkedin_poster.py --dry-run --content "Test"
        """,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--content", help="Post text (pass as string)")
    group.add_argument("--draft",   help="Path to DRAFT_POST_*.md file")

    parser.add_argument("--dry-run", action="store_true", help="Log without posting")
    args = parser.parse_args()

    # Resolve content
    if args.draft:
        draft_path = Path(args.draft)
        if not draft_path.exists():
            # Try relative to vault root
            draft_path = _VAULT_ROOT / args.draft
        if not draft_path.exists():
            log.error("Draft file not found: %s", args.draft)
            sys.exit(3)
        try:
            content = extract_post_from_draft(draft_path)
        except ValueError as exc:
            log.error("%s", exc)
            sys.exit(3)
        log.info("Content loaded from draft: %s (%d chars)", draft_path.name, len(content))
    else:
        content = args.content

    if not content.strip():
        log.error("Post content is empty.")
        sys.exit(3)

    poster = LinkedInPoster(dry_run=args.dry_run)

    try:
        success = poster.post(content)
    except Exception as exc:
        log.exception("Unexpected error: %s", exc)
        sys.exit(1)

    if success:
        log.info("LinkedIn post complete.")
        _log_activity(
            f"SKILL-008 | linkedin_poster | posted to LinkedIn | "
            f"{'DRY-RUN' if args.dry_run else 'LIVE'} | {len(content)} chars"
        )
        sys.exit(0)
    else:
        log.error("LinkedIn post failed — check Logs/LinkedInPoster.log for details.")
        sys.exit(1)


if __name__ == "__main__":
    main()
